### ISSUE TITLE
[Bug] Job posts pulling through Lorum Ipsum

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/canonical.com#128] opened 2019-12-19 16:41 UTC
When you job roles are presented to you they show lorum ipsum

![Screenshot 2019-12-19 at 16.40.18.png](https://images.zenhubusercontent.com/5cb4608c97df763a9090bdeb/4146ab37-1761-45aa-9a90-eb206235328a)

**Comment by sowasred2012** [comment] 2019-12-19 17:05
Closing as duplicate of #126

**Closed** 2019-12-19 17:05 UTC
